name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'MultiplayerExtensions.VoiceChat/**'
      - '.github/workflows/Build.yml'
      - 'Refs/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'MultiplayerExtensions.VoiceChat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: GetStrippedRefs
      env:
        FILES_URL: ${{ secrets.BSFILES_URL }}
      run: wget --no-check-certificate "$FILES_URL" -q -O bsfiles.zip
    - name: ExtractRefs
      run: unzip -q -n bsfiles.zip -d ./Refs
    - name: ExtractMpExRefs
      run: unzip -q -n bsfiles.zip -d ./MultiplayerExtensions/Refs
    - name: Restore
      run: dotnet restore
    - name: Check Nuget
      run: ll /home/runner/.nuget/packages/system.runtime/4.3.0/lib
    - name: Build
      id: Build
      env: 
        FrameworkPathOverride: /usr/lib/mono/4.8-api
      run: dotnet build --configuration Release --no-restore
    - name: GitStatus
      run: git status
    - name: Echo Filename
      run: echo $BUILDTEXT \($ASSEMBLYNAME\)
      env:
        BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
        ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ${{ steps.Build.outputs.artifactpath }}
